<#
.SYNOPSIS
    Forage Radio - Terminal Realtime Radio (PowerShell)
.DESCRIPTION
    Plays tracks generated by your ComfyUI (ACE-Step / Stable Audio) as a live radio.
    Run this with the .bat launcher for best results.
#>

param(
    [string]$AudioPath = "Z:\C0MFY\ComfyUI\output\audio"
)

Write-Host "=== FORAGE RADIO (PowerShell) ===" -ForegroundColor Cyan
Write-Host "Scanning for tracks in: $AudioPath" -ForegroundColor Gray
Write-Host ""

# Make errors visible
$ErrorActionPreference = "Continue"

# Try to locate ffplay
$ffplay = $null
$candidates = @(
    "ffplay.exe",
    "C:\ffmpeg\bin\ffplay.exe",
    "C:\Program Files\ffmpeg\bin\ffplay.exe",
    "$env:LOCALAPPDATA\Programs\ffmpeg\bin\ffplay.exe",
    "C:\C0MFY\ffmpeg\bin\ffplay.exe"   # common location some people use
)

foreach ($c in $candidates) {
    if (Get-Command $c -ErrorAction SilentlyContinue) {
        $ffplay = $c
        break
    }
    if (Test-Path $c) {
        $ffplay = $c
        break
    }
}

if (-not $ffplay) {
    Write-Host "ERROR: ffplay.exe was not found!" -ForegroundColor Red
    Write-Host "Please install ffmpeg (https://ffmpeg.org) and make sure ffplay is in your PATH." -ForegroundColor Yellow
    Write-Host ""
    Read-Host "Press Enter to exit"
    exit
}

Write-Host "Using ffplay: $ffplay" -ForegroundColor Green

function Get-TrackList {
    if (-not (Test-Path $AudioPath)) {
        Write-Host "Warning: Audio folder does not exist: $AudioPath" -ForegroundColor Yellow
        return @()
    }

    Get-ChildItem -Path $AudioPath -Filter "*.mp3" -File -ErrorAction SilentlyContinue |
        Sort-Object LastWriteTime -Descending |
        Select-Object -First 40 |
        ForEach-Object {
            [PSCustomObject]@{
                FullPath = $_.FullName
                Name     = ($_.BaseName -replace '_', ' ').Trim()
                FileName = $_.Name
            }
        }
}

$playlist = Get-TrackList
$currentIndex = 0
$playingProcess = $null
$isPlaying = $false

function Stop-Current {
    if ($playingProcess -and -not $playingProcess.HasExited) {
        try { $playingProcess.Kill() } catch {}
        Start-Sleep -Milliseconds 300
    }
    $script:playingProcess = $null
    $script:isPlaying = $false
}

function Play-Track($index) {
    if ($index -lt 0 -or $index -ge $playlist.Count) { return }

    Stop-Current

    $track = $playlist[$index]
    $script:currentIndex = $index
    $script:isPlaying = true

    Write-Host "`n▶ Now Playing: $($track.Name)" -ForegroundColor Cyan

    $script:playingProcess = Start-Process -FilePath $ffplay `
        -ArgumentList @("-nodisp", "-autoexit", "-loglevel", "error", "`"$($track.FullPath)`"") `
        -PassThru -WindowStyle Hidden

    # Simple auto-advance watcher
    Start-Job -ScriptBlock {
        param($proc)
        $proc.WaitForExit()
        "NEXT_TRACK" | Out-File "$env:TEMP\forage-radio-next.txt" -Force
    } -ArgumentList $playingProcess | Out-Null
}

function Show-Screen {
    Clear-Host
    Write-Host "╔══════════════════════════════════════════════════════════════╗" -ForegroundColor Cyan
    Write-Host "║                    FORAGE RADIO (PowerShell)                 ║" -ForegroundColor Cyan
    Write-Host "╚══════════════════════════════════════════════════════════════╝" -ForegroundColor Cyan
    Write-Host ""

    if ($playlist.Count -eq 0) {
        Write-Host "No .mp3 files found in:" -ForegroundColor Yellow
        Write-Host "  $AudioPath" -ForegroundColor Gray
        Write-Host ""
        Write-Host "Generate some tracks in ComfyUI, then press R to refresh." -ForegroundColor Yellow
        return
    }

    $current = $playlist[$currentIndex]
    Write-Host "NOW PLAYING" -ForegroundColor Magenta
    Write-Host "  $($current.Name)" -ForegroundColor White
    Write-Host ""

    Write-Host "PLAYLIST ($($playlist.Count) tracks)" -ForegroundColor Yellow
    for ($i = 0; $i -lt $playlist.Count; $i++) {
        $marker = if ($i -eq $currentIndex) { "► " } else { "  " }
        $color = if ($i -eq $currentIndex) { "Cyan" } else { "White" }
        Write-Host ("$marker{0,2}. {1}" -f ($i+1), $playlist[$i].Name) -ForegroundColor $color
    }

    Write-Host ""
    Write-Host "Controls: [Space]=Play/Pause  [N]=Next  [P]=Prev  [R]=Refresh  [Q]=Quit" -ForegroundColor Green
}

function Refresh-Playlist {
    $script:playlist = Get-TrackList
    Write-Host "`n[Refreshed - $($playlist.Count) tracks]" -ForegroundColor Green
}

# === Main ===
Show-Screen

if ($playlist.Count -gt 0) {
    Play-Track 0
}

while ($true) {
    # Check for auto-advance signal
    $signal = "$env:TEMP\forage-radio-next.txt"
    if (Test-Path $signal) {
        Remove-Item $signal -Force -ErrorAction SilentlyContinue
        $next = ($currentIndex + 1) % $playlist.Count
        Play-Track $next
        Show-Screen
    }

    if ([Console]::KeyAvailable) {
        $key = [Console]::ReadKey($true).Key

        switch ($key) {
            'Spacebar' {
                if ($isPlaying) {
                    Stop-Current
                } else {
                    if ($playlist.Count -gt 0) {
                        Play-Track $currentIndex
                    }
                }
                Show-Screen
            }
            'N' { 
                $next = ($currentIndex + 1) % $playlist.Count
                Play-Track $next
                Show-Screen 
            }
            'P' { 
                $prev = ($currentIndex - 1 + $playlist.Count) % $playlist.Count
                Play-Track $prev
                Show-Screen 
            }
            'R' { 
                Refresh-Playlist
                Show-Screen 
            }
            'Q' { 
                Stop-Current
                Write-Host "`nThanks for listening!" -ForegroundColor Cyan
                Start-Sleep -Seconds 1
                exit 
            }
        }
    }

    Start-Sleep -Milliseconds 120
}

# Safety net - keep window open if something goes wrong
Read-Host "`nPress Enter to close window"
